In [1]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist

(x_train, y_train),(x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model.fit(x_train, y_train, epochs=5)
model.evaluate(x_test, y_test)

11501568/11490434 [==============================] - 0s 0us/step
Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2954 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1444 - accuracy: 0.9565
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1091 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0865 - accuracy: 0.9735
Epoch 5/5
313/313 [==============================] - 1s 1ms/step - loss: 0.0756 - accuracy: 0.9771


[0.0755547359585762, 0.9771000146865845]

In [2]:
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.8.0


Load Dataset

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

Build a machine learning model

In [4]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [5]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.37944683, -0.13245209, -0.29712296, -0.06310437, -0.05443017,
        -0.83919793, -0.46372676, -0.34706736,  0.7609518 , -0.5070806 ]],
      dtype=float32)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.07865439, 0.10069118, 0.08540352, 0.10792169, 0.1088619 ,
        0.04966559, 0.07229707, 0.08124286, 0.24603212, 0.06922968]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [8]:
loss_fn(y_train[:1], predictions).numpy()

3.0024428

In [9]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

Train and evaluate model

In [10]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.3017 - accuracy: 0.9110
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1462 - accuracy: 0.9567
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1092 - accuracy: 0.9672
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0901 - accuracy: 0.9724
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0762 - accuracy: 0.9762


In [11]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0815 - accuracy: 0.9727 - 721ms/epoch - 2ms/step


[0.0814586877822876, 0.9726999998092651]

In [12]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])


In [13]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[7.10071276e-07, 2.85810930e-10, 6.91136074e-06, 1.26365587e-04,
        2.68711747e-10, 1.12386713e-08, 7.26053603e-13, 9.99857187e-01,
        5.95217500e-07, 8.26462474e-06],
       [7.69893745e-07, 3.65146319e-04, 9.99563992e-01, 5.80595733e-05,
        5.39876778e-16, 2.61794426e-08, 5.96549583e-08, 5.38421467e-13,
        1.19384185e-05, 9.00648566e-12],
       [3.92133984e-07, 9.99385118e-01, 5.10166792e-05, 1.91597010e-05,
        1.22935899e-05, 9.81069775e-07, 1.26798022e-05, 4.75402368e-04,
        4.26236329e-05, 3.38954209e-07],
       [9.99962568e-01, 2.67462807e-09, 1.66962818e-05, 3.27242930e-07,
        3.64900714e-08, 1.16198564e-07, 1.02877138e-05, 2.62405365e-06,
        1.38522340e-08, 7.36836409e-06],
       [4.94022024e-05, 5.88160187e-09, 1.98276957e-05, 6.96077294e-08,
        9.82682586e-01, 2.48387352e-07, 2.38066496e-05, 2.74845253e-04,
        1.74804416e-06, 1.69475079e-02]], dtype=float32)>